version: '3'
services:
  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: 'Asia/Ho_Chi_Minh'
    networks:
      - bun-networks
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
  redis:
    image: redis:latest
    networks:
      - bun-networks
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
networks:
  bun-networks:
    driver: bridge
