import { z } from 'zod'
import { AppRequest } from './abstract'

export type HTTPMethod =
  | 'ACL'
  | 'BIND'
  | 'CHECKOUT'
  | 'CONNECT'
  | 'COPY'
  | 'DELETE'
  | 'GET'
  | 'HEAD'
  | 'LINK'
  | 'LOCK'
  | 'M-SEARCH'
  | 'MERGE'
  | 'MKACTIVITY'
  | 'MKCALENDAR'
  | 'MKCOL'
  | 'MOVE'
  | 'NOTIFY'
  | 'OPTIONS'
  | 'PATCH'
  | 'POST'
  | 'PROPFIND'
  | 'PROPPATCH'
  | 'PURGE'
  | 'PUT'
  | 'REBIND'
  | 'REPORT'
  | 'SEARCH'
  | 'SOURCE'
  | 'SUBSCRIBE'
  | 'TRACE'
  | 'UNBIND'
  | 'UNLINK'
  | 'UNLOCK'
  | 'UNSUBSCRIBE'
  | 'ALL'

export interface IRoute {
  handler: (req: AppRequest) => Promise<any>
  url: string
  schema?: z.ZodObject<any>
  middleware?: string | string[]
  requireAuth?: boolean
}

export interface RequestUser {
  id: number
  email: string
  name: string | null
  created_at: Date
  updated_at: Date
}
export interface JWTPayload extends RequestUser {
  exp: number
  iat: number
}

// Generated by https://quicktype.io

export interface SapoOrder {
  id: number
  buyer_accepts_marketing: boolean
  cancel_reason: null
  cancelled_on: null
  cart_token: string
  checkout_token: string
  closed_on: null
  created_on: string
  currency: string
  email: string
  phone: string
  fulfillment_status: null
  financial_status: string
  status: string
  name: string
  note: string
  number: number
  order_number: number
  processed_on: string
  processing_method: string
  source_url: null
  source_name: string
  source: string
  landing_site: string
  landing_site_ref: null
  referring_site: string
  reference: null
  source_identifier: null
  gateway: string
  sub_total_price: number
  token: string
  total_discounts: number
  total_line_items_price: number
  total_price: number
  total_weight: number
  modified_on: string
  tags: null
  pay_adjustment_status: null
  test: boolean
  billing_address: Address
  shipping_address: Address
  customer: Customer
  client_details: ClientDetails
  line_items: LineItem[]
  shipping_lines: ShippingLine[]
  fulfillments: any[]
  refunds: any[]
  note_attributes: any[]
  discount_codes: any[]
  discount_applications: any[]
  app: App
  channel_definition: ChannelDefinition
  user_id: null
  assignee_id: null
  location_id: null
  payment_gateway_names: string[]
  can_mark_as_paid: boolean
  capturable: boolean
  tax_exempt: boolean
  taxes_included: boolean
  tax_lines: any[]
  total_shipping_price: number
  total_tax: number
  original_total_price: number
  cart_discount_amount: number
  net_payment: number
  unpaid_amount: number
  total_outstanding: number
  total_received: number
  total_refunded: number
  total_refunded_shipping: number
  current_cart_discount_amount: number
  current_total_discounts: number
  current_subtotal_price: number
  current_total_price: number
  current_total_tax: number
  current_tax_lines: any[]
  edited: boolean
  can_notify_customer: boolean
  subtotal_line_items_quantity: number
  current_total_weight: number
  current_discounted_total: number
  merchant_editable_errors: null
  current_subtotal_line_items_quantity: number
  browser_ip: string
  merchant_editable: boolean
  refundable: boolean
}

export interface App {
  id: number
  key: string
  alias: string
}

export interface Address {
  address1: string
  address2: null
  city: string
  first_name: string
  last_name: null
  phone: string
  province: string
  province_code: string
  zip: null
  country_code: string
  country_name?: string
  company: null
  country: string
  name?: string
  district: string
  district_code: string
  ward: null
  ward_code: null
  latitude?: null
  longitude?: null
  id?: number
  default?: boolean
}

export interface ChannelDefinition {
  id: number
  main_name: string
  sub_name: string
  alias: string
}

export interface ClientDetails {
  browser_ip: string
  accept_language: null
  user_agent: string
  session_hash: null
  browser_width: number
  browser_height: number
}

export interface Customer {
  id: number
  state: string
  email: string
  phone: string
  first_name: string
  last_name: null
  dob: null
  note: null
  tags: null
  gender: string
  last_order_name: string
  last_order_id: number
  total_spent: number
  orders_count: number
  accepts_marketing: boolean
  verified_email: boolean
  default_address: Address
  created_on: string
  modified_on: string
}

export interface LineItem {
  id: number
  price: number
  total_discount: number
  discount_code: null
  fulfillment_status: null
  fulfillable_quantity: number
  quantity: number
  current_quantity: number
  grams: number
  product_id: number
  variant_id: number
  inventory_item_id: null
  product_exists: boolean
  variant_inventory_management: string
  requires_shipping: boolean
  name: string
  title: string
  variant_title: string
  sku: string
  vendor: string
  gift_card: boolean
  properties: any[]
  discount_allocations: any[]
  tax_lines: any[]
  taxable: boolean
  non_fulfillable_quantity: number
  refundable_quantity: number
  restockable: boolean
  discounted_unit_price: number
  discounted_total: number
  original_total: number
  fulfillment_service: string
  merchant_editable: boolean
}

export interface ShippingLine {
  title: string
  code: string
  source: null
  price: number
  discount_allocations: any[]
  tax_lines: any[]
}
